### 🧾 Get all authors + their books
GET http://localhost:5086/authors/test-authors
Accept: application/json

###

### ➕ Add a book to an author
POST http://localhost:5086/authors/3/add-book/2001
Content-Type: application/json

{
  "notes": "Attaching book with ISBN 2 to author 2"
}

### 🆕 Add a brand new book
POST http://localhost:5086/add-book
Content-Type: application/json

{
  "title": "The Silmarillion",
  "price": 25.99,
  "discount": 0.1
}

### ✍️ Add a new author
POST http://localhost:5086/authors
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Green"
}

### 🧾 Get all books + author
GET http://localhost:5086/books
Accept: application/json

### 🆕 Update a book
PUT http://localhost:5086/update-book
Content-Type: application/json

{
  "isbn": 1,
  "authors" : [{}]
}

### Delete a book
DELETE http://localhost:5086/delete-book/1
Content-Type: application/json

{
  "notes": "Removing book"
}